-- ATTENDANCE_RECORDS
CREATE INDEX IDX_ATTENDANCE_DATE ON ATTENDANCE_RECORDS(DATE_ATTENDED);
CREATE INDEX IDX_ATTENDANCE_ENROLLMENT ON ATTENDANCE_RECORDS(ENROLLMENT_ID);
CREATE INDEX IDX_ATTENDANCE_STATUS ON ATTENDANCE_RECORDS(STATUS);
CREATE INDEX SYS_C007577 ON ATTENDANCE_RECORDS(RECORD_ID);

-- BOOK_LOANS
CREATE INDEX IDX_LOANS_BOOK ON BOOK_LOANS(BOOK_ID);
CREATE INDEX IDX_LOANS_DATES ON BOOK_LOANS(LOAN_DATE,RETURN_DATE);
CREATE INDEX IDX_LOANS_STUDENT ON BOOK_LOANS(STUDENT_ID);
CREATE INDEX SYS_C007585 ON BOOK_LOANS(LOAN_ID);

-- CLASSROOMS
CREATE INDEX SYS_C007558 ON CLASSROOMS(ROOM_ID);

-- COURSES
CREATE INDEX IDX_COURSES_DEPT ON COURSES(DEPT_ID);
CREATE INDEX IDX_COURSES_NAME_DEPT ON COURSES(COURSE_NAME,DEPT_ID);
CREATE INDEX SYS_C007555 ON COURSES(COURSE_ID);
CREATE INDEX SYS_C007556 ON COURSES(COURSE_CODE);

-- COURSE_OFFERINGS
CREATE INDEX SYS_C007568 ON COURSE_OFFERINGS(OFFERING_ID);

-- COURSE_PREREQUISITES
CREATE INDEX SYS_C007565 ON COURSE_PREREQUISITES(COURSE_ID,PREREQUISITE_ID);

-- DEPARTMENTS
CREATE INDEX IDX_DEPARTMENTS_NAME ON DEPARTMENTS(DEPT_NAME);
CREATE INDEX SYS_C007546 ON DEPARTMENTS(DEPT_ID);

-- DISCIPLINARY_ACTIONS
CREATE INDEX IDX_DISCIPLINARY_ACTIONS_FACULTY_ID ON DISCIPLINARY_ACTIONS(FACULTY_ID);
CREATE INDEX IDX_DISCIPLINARY_ACTIONS_STUDENT_ID ON DISCIPLINARY_ACTIONS(STUDENT_ID);
CREATE INDEX IDX_DISCIPLINARY_DATE ON DISCIPLINARY_ACTIONS(ACTION_DATE);
CREATE INDEX SYS_C007592 ON DISCIPLINARY_ACTIONS(ACTION_ID);

-- ENROLLMENTS
CREATE INDEX IDX_ENROLLMENTS_COURSE_ID ON ENROLLMENTS(COURSE_ID);
CREATE INDEX IDX_ENROLLMENTS_GRADE ON ENROLLMENTS(GRADE);
CREATE INDEX IDX_ENROLLMENTS_SEMESTER_CODE ON ENROLLMENTS(SEMESTER_CODE);
CREATE INDEX IDX_ENROLLMENTS_STUDENT_ID ON ENROLLMENTS(STUDENT_ID);
CREATE INDEX IDX_ENROLLMENTS_STUDENT_SEMESTER ON ENROLLMENTS(STUDENT_ID,SEMESTER_CODE);
CREATE INDEX SYS_C007572 ON ENROLLMENTS(ENROLLMENT_ID);

-- EXAMS
CREATE INDEX IDX_EXAMS_COURSE_SEMESTER ON EXAMS(COURSE_ID,SEMESTER_CODE);
CREATE INDEX SYS_C007599 ON EXAMS(EXAM_ID);

-- EXAM_RESULTS
CREATE INDEX IDX_RESULTS_EXAM ON EXAM_RESULTS(EXAM_ID);
CREATE INDEX IDX_RESULTS_STUDENT ON EXAM_RESULTS(STUDENT_ID);
CREATE INDEX IDX_RESULTS_STUDENT_EXAM ON EXAM_RESULTS(STUDENT_ID,EXAM_ID);
CREATE INDEX SYS_C007602 ON EXAM_RESULTS(RESULT_ID);

-- FACULTY
CREATE INDEX IDX_FACULTY_DEPT ON FACULTY(DEPT_ID);
CREATE INDEX IDX_FACULTY_HIRE_DATE ON FACULTY(HIRE_DATE);
CREATE INDEX SYS_C007552 ON FACULTY(FACULTY_ID);
CREATE INDEX SYS_C007553 ON FACULTY(EMAIL);

-- FEES
CREATE INDEX IDX_FEES_DUE_DATE ON FEES(DUE_DATE);
CREATE INDEX IDX_FEES_STUDENT ON FEES(STUDENT_ID);
CREATE INDEX SYS_C007579 ON FEES(FEE_ID);

-- GRADES
CREATE INDEX SYS_C007571 ON GRADES(GRADE);

-- HOSTELS
CREATE INDEX SYS_C007588 ON HOSTELS(HOSTEL_ID);

-- HOSTEL_ALLOCATIONS
CREATE INDEX IDX_ALLOCATIONS_DATE ON HOSTEL_ALLOCATIONS(ALLOCATION_DATE);
CREATE INDEX IDX_HOSTEL_ALLOCATIONS_HOSTEL_ID ON HOSTEL_ALLOCATIONS(HOSTEL_ID);
CREATE INDEX IDX_HOSTEL_ALLOCATIONS_STUDENT_ID ON HOSTEL_ALLOCATIONS(STUDENT_ID);
CREATE INDEX SYS_C007589 ON HOSTEL_ALLOCATIONS(ALLOC_ID);

-- LIBRARY_BOOKS
CREATE INDEX SYS_C007583 ON LIBRARY_BOOKS(BOOK_ID);
CREATE INDEX SYS_C007584 ON LIBRARY_BOOKS(ISBN);

-- NOTIFICATIONS
CREATE INDEX IDX_NOTIFICATIONS_DATE ON NOTIFICATIONS(SENT_DATE);
CREATE INDEX IDX_NOTIFICATIONS_FACULTY ON NOTIFICATIONS(FACULTY_ID);
CREATE INDEX IDX_NOTIFICATIONS_STUDENT ON NOTIFICATIONS(STUDENT_ID);
CREATE INDEX SYS_C007606 ON NOTIFICATIONS(NOTIFICATION_ID);

-- PAYMENTS
CREATE INDEX IDX_PAYMENTS_DATE ON PAYMENTS(PAYMENT_DATE);
CREATE INDEX IDX_PAYMENTS_FEE ON PAYMENTS(FEE_ID);
CREATE INDEX SYS_C007581 ON PAYMENTS(PAYMENT_ID);

-- SCHEDULES
CREATE INDEX IDX_SCHEDULES_COURSE ON SCHEDULES(COURSE_ID);
CREATE INDEX IDX_SCHEDULES_FACULTY ON SCHEDULES(FACULTY_ID);
CREATE INDEX IDX_SCHEDULES_ROOM ON SCHEDULES(ROOM_ID);
CREATE INDEX IDX_SCHEDULES_SEMESTER ON SCHEDULES(SEMESTER_CODE);
CREATE INDEX IDX_SCHEDULES_TIME ON SCHEDULES(SCHEDULE_TIME);
CREATE INDEX SYS_C007560 ON SCHEDULES(SCHEDULE_ID);

-- SCHOLARSHIPS
CREATE INDEX SYS_C007595 ON SCHOLARSHIPS(SCHOLARSHIP_ID);

-- SEMESTERS
CREATE INDEX SYS_C007559 ON SEMESTERS(SEMESTER_CODE);

-- STUDENTS
CREATE INDEX IDX_STUDENTS_DEPT ON STUDENTS(DEPT_ID);
CREATE INDEX IDX_STUDENTS_ENROLLMENT_DATE ON STUDENTS(ENROLLMENT_DATE);
CREATE INDEX SYS_C007548 ON STUDENTS(STUDENT_ID);
CREATE INDEX SYS_C007549 ON STUDENTS(EMAIL);

-- STUDENT_SCHOLARSHIPS
CREATE INDEX IDX_SCHOLARSHIPS_DATE ON STUDENT_SCHOLARSHIPS(AWARD_DATE);
CREATE INDEX IDX_SCHOLARSHIPS_STUDENT ON STUDENT_SCHOLARSHIPS(STUDENT_ID);
CREATE INDEX IDX_SCHOLARSHIPS_TYPE ON STUDENT_SCHOLARSHIPS(SCHOLARSHIP_ID);
CREATE INDEX SYS_C007596 ON STUDENT_SCHOLARSHIPS(STUDENT_SCHOLARSHIP_ID);