-- ATTENDANCE_RECORDS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_ATTENDANCE_RECORDS
BEFORE INSERT ON attendance_records
FOR EACH ROW
WHEN (NEW.record_id IS NULL)
BEGIN
  SELECT seq_attendance_records.NEXTVAL INTO :NEW.record_id FROM dual;
END;
/

-- BOOK_LOANS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_BOOK_LOANS
BEFORE INSERT ON book_loans
FOR EACH ROW
WHEN (NEW.loan_id IS NULL)
BEGIN
  SELECT seq_book_loans.NEXTVAL INTO :NEW.loan_id FROM dual;
END;
/

-- COURSES
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_COURSES
BEFORE INSERT ON courses
FOR EACH ROW
WHEN (NEW.course_id IS NULL)
BEGIN
  SELECT seq_courses.NEXTVAL INTO :NEW.course_id FROM dual;
END;
/

-- COURSE_OFFERINGS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_COURSE_OFFERINGS
BEFORE INSERT ON course_offerings
FOR EACH ROW
WHEN (NEW.offering_id IS NULL)
BEGIN
  SELECT seq_course_offerings.NEXTVAL INTO :NEW.offering_id FROM dual;
END;
/

-- DEPARTMENTS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_DEPARTMENTS
BEFORE INSERT ON departments
FOR EACH ROW
WHEN (NEW.dept_id IS NULL)
BEGIN
  SELECT seq_departments.NEXTVAL INTO :NEW.dept_id FROM dual;
END;
/

-- DISCIPLINARY_ACTIONS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_DISCIPLINARY_ACTIONS
BEFORE INSERT ON disciplinary_actions
FOR EACH ROW
WHEN (NEW.action_id IS NULL)
BEGIN
  SELECT seq_disciplinary_actions.NEXTVAL INTO :NEW.action_id FROM dual;
END;
/

-- ENROLLMENTS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_ENROLLMENTS
BEFORE INSERT ON enrollments
FOR EACH ROW
WHEN (NEW.enrollment_id IS NULL)
BEGIN
  SELECT seq_enrollments.NEXTVAL INTO :NEW.enrollment_id FROM dual;
END;
/

-- EXAMS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_EXAMS
BEFORE INSERT ON exams
FOR EACH ROW
WHEN (NEW.exam_id IS NULL)
BEGIN
  SELECT seq_exams.NEXTVAL INTO :NEW.exam_id FROM dual;
END;
/

-- EXAM_RESULTS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_EXAM_RESULTS
BEFORE INSERT ON exam_results
FOR EACH ROW
WHEN (NEW.result_id IS NULL)
BEGIN
  SELECT seq_exam_results.NEXTVAL INTO :NEW.result_id FROM dual;
END;
/

-- FACULTY
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_FACULTY
BEFORE INSERT ON faculty
FOR EACH ROW
WHEN (NEW.faculty_id IS NULL)
BEGIN
  SELECT seq_faculty.NEXTVAL INTO :NEW.faculty_id FROM dual;
END;
/

-- FEES
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_FEES
BEFORE INSERT ON fees
FOR EACH ROW
WHEN (NEW.fee_id IS NULL)
BEGIN
  SELECT seq_fees.NEXTVAL INTO :NEW.fee_id FROM dual;
END;
/

-- HOSTELS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_HOSTELS
BEFORE INSERT ON hostels
FOR EACH ROW
WHEN (NEW.hostel_id IS NULL)
BEGIN
  SELECT seq_hostels.NEXTVAL INTO :NEW.hostel_id FROM dual;
END;
/

-- HOSTEL_ALLOCATIONS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_HOSTEL_ALLOCATIONS
BEFORE INSERT ON hostel_allocations
FOR EACH ROW
WHEN (NEW.alloc_id IS NULL)
BEGIN
  SELECT seq_hostel_allocations.NEXTVAL INTO :NEW.alloc_id FROM dual;
END;
/

-- LIBRARY_BOOKS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_LIBRARY_BOOKS
BEFORE INSERT ON library_books
FOR EACH ROW
WHEN (NEW.book_id IS NULL)
BEGIN
  SELECT seq_library_books.NEXTVAL INTO :NEW.book_id FROM dual;
END;
/

-- NOTIFICATIONS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_NOTIFICATIONS
BEFORE INSERT ON notifications
FOR EACH ROW
WHEN (NEW.notification_id IS NULL)
BEGIN
  SELECT seq_notifications.NEXTVAL INTO :NEW.notification_id FROM dual;
END;
/

-- PAYMENTS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_PAYMENTS
BEFORE INSERT ON payments
FOR EACH ROW
WHEN (NEW.payment_id IS NULL)
BEGIN
  SELECT seq_payments.NEXTVAL INTO :NEW.payment_id FROM dual;
END;
/

-- SCHEDULES
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_SCHEDULES
BEFORE INSERT ON schedules
FOR EACH ROW
WHEN (NEW.schedule_id IS NULL)
BEGIN
  SELECT seq_schedules.NEXTVAL INTO :NEW.schedule_id FROM dual;
END;
/

-- SCHOLARSHIPS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_SCHOLARSHIPS
BEFORE INSERT ON scholarships
FOR EACH ROW
WHEN (NEW.scholarship_id IS NULL)
BEGIN
  SELECT seq_scholarships.NEXTVAL INTO :NEW.scholarship_id FROM dual;
END;
/

-- STUDENTS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_STUDENTS
BEFORE INSERT ON students
FOR EACH ROW
WHEN (NEW.student_id IS NULL)
BEGIN
  SELECT seq_students.NEXTVAL INTO :NEW.student_id FROM dual;
END;
/

-- STUDENT_SCHOLARSHIPS
CREATE OR REPLACE EDITIONABLE TRIGGER UNIVOFFICE.TRG_STUDENT_SCHOLARSHIPS
BEFORE INSERT ON student_scholarships
FOR EACH ROW
WHEN (NEW.student_scholarship_id IS NULL)
BEGIN
  SELECT seq_student_scholarships.NEXTVAL INTO :NEW.student_scholarship_id FROM dual;
END;
/
